export const metadata = {
  title: "Fitwise",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo.png" sizes="32x32" />
        <title>Fitwise</title>
      </head>
      <body>{children}</body>
    </html>
  );
}
